/**
 * Created by ytang on 2018/9/14.
 */

 /**
 * action对象的type属性集合
 */
const actionType = {
    FETCH_LOADING_SUFFIX : '_LOADING',
    FETCH_SUCCESS_SUFFIX : '_SUCCESS',
    FETCH_ERROR_SUFFIX : '_ERROR',
    
    FETCH_SHOW_HUD: 'FETCH_SHOW_HUD',

    MOVIE_LIST: 'MOVIE_LIST',
    MOVIE_SHOWTIME_LIST: 'MOVIE_SHOWTIME_LIST',
    MOVIE_COMEING_NEW_LIST: 'MOVIE_COMEING_NEW_LIST',
    MOVIE_TRAILER_LIST: 'MOVIE_TRAILER_LIST',

    // router
    REACT_NATIVE_ROUTER_FLUX_SET_PARAMS: 'Navigation/SET_PARAMS',
    REACT_NATIVE_ROUTER_FLUX_EVENT: 'REACT_NATIVE_ROUTER_FLUX_EVENT',
    REACT_NATIVE_ROUTER_FLUX_EVENT_CLEAR: 'REACT_NATIVE_ROUTER_FLUX_EVENT_CLEAR',
    REACT_NATIVE_ROUTER_FLUX_BACK: 'Navigation/BACK',
    REACT_NATIVE_ROUTER_FLUX_BLUR: 'REACT_NATIVE_ROUTER_FLUX_BLUR',
    REACT_NATIVE_ROUTER_FLUX_FOCUS: 'REACT_NATIVE_ROUTER_FLUX_FOCUS',
    REACT_NATIVE_ROUTER_FLUX_REPLACE: 'REACT_NATIVE_ROUTER_FLUX_REPLACE',
    REACT_NATIVE_ROUTER_FLUX_SET_PARAMS: 'Navigation/SET_PARAMS'
}

export default actionType